### ISSUE TITLE
An alternative use of class names

### ISSUE THREAD

**Issue by mgiulio** [christianvuerings/jquery-lifestream#12]
I experimented with this on https://github.com/mgiulio/jquery-lifestream/commit/e66485bf1f12484feb4928260587efd8ccc73e1c . But to note that there can be troubles with CSS decls like

``` css
#lifestream .activity:hover {
      color: #e9e9e9;
}
```

so I didn't sent a pull request. Just something to think about.
