### ISSUE TITLE
BUG: Newlines are not displayed

### ISSUE THREAD

**Issue by westurner** [christianvuerings/jquery-lifestream#184]
Solution:

In `examples.html`, add:

``` css
ul.lifestream li { white-space: pre-wrap; }
```
